DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS sdrumos;
DROP TABLE IF EXISTS busses;
DROP TABLE IF EXISTS sdrumo_busses;
DROP TABLE IF EXISTS refresh_tokens;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sdrumos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  user_id INTEGER DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  location TEXT,
  location_latitude REAL,
  location_longitude REAL,
  stop_id INTEGER,

  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE busses (
  id INTEGER PRIMARY KEY,
  bus_number TEXT NOT NULL,
  bus_name TEXT NOT NULL,
  color TEXT
);

CREATE TABLE sdrumo_busses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sdrumo_id INTEGER NOT NULL,
  bus_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  FOREIGN KEY (sdrumo_id) REFERENCES sdrumos (id) ON DELETE CASCADE,
  FOREIGN KEY (bus_id) REFERENCES busses (id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    jti TEXT NOT NULL UNIQUE,
    revoked BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
  
INSERT INTO busses (id, bus_number, bus_name, color) VALUES
(580, '6', 'Costa Corso Rosmini S.Giorgio/Ospedale', 'None'),
(69, 'B402', 'Trento - Nogarè - Baselga di Pinè -Montesover', 'None'),
(84, 'B429', 'Centrale - Regnana', 'None'),
(86, 'B408', 'Borgo Valsugana - Olle', 'None'),
(90, 'B415', 'Levico Terme - Barco - S.Giuliana - Lochere', 'None'),
(92, 'B431', 'Baselga di Pinè - S.Mauro', 'None'),
(94, 'B413', 'Brusago-Valcava', 'None'),
(96, 'B428', 'Bedollo-Svaldi', 'None'),
(98, 'B410', 'Borgo Valsugana - Tezze - Primolano', 'None'),
(132, 'B409', 'Borgo Valsugana -Roncegno Terme -Ronchi', 'None'),
(138, 'B404', ' Baselga di Pinè - Faida', 'None'),
(102, 'B501', 'S.Martino di Castrozza-Fiera di Primiero-Feltre', 'None'),
(106, 'B504', 'Canal S.Bovo - Ronco Fosse - Ronco Chiesa', 'None'),
(108, 'B512', 'Trento-Borgo Valsugana-Arten-Feltre', 'None'),
(531, 'Fu', 'Funivia Trento Sardagna', 'None'),
(396, '3', 'Cortesano Gardolo P.Dante Villazzano 3', 'C52720'),
(400, '5', 'Piazza Dante P.Fiera Povo Oltrecastello', 'F5C500'),
(402, '7', 'Canova Melta Piazza Dante Gocciadoro', '0A9B86'),
(404, '8', 'Centochiavi Piazza Dante Mattarello', '52332A'),
(406, '9', 'P.Dante S.Donà Cognola Villamontagna', '8B4E2B'),
(408, '10', 'P.Dante Martignano Cognola / Montevaccino', '0A5543'),
(425, '11', 'Dogana Ftm Via Brennero Gardolo Spini', '582E79'),
(466, '13', 'P.Dante Rosmini S.Rocco Povo Polo Soc.', 'BF6092'),
(478, '15', 'Dogana Ftm Interporto Spini Di Gardolo', '72E006'),
(484, '16', 'Centochiavi Martignano Cognola Povo', '3564B1'),
(533, 'C', 'Rsa "S.Bart." "Angeli Custodi" Laste', '000000'),
(535, '5/', 'P.Dante P.Fiera Università Mesiano Povo', 'None'),
(536, '1', 'Ospedale P.Dante Sopramonte', '1D3F72'),
(538, '2', 'Piedic. Stazione Osp.S.Chiara Regione Piedic.', 'DB5826'),
(539, '4', 'Gardolo Roncafort Stazione V.Deg. Mad.Bianca', '007BC3'),
(541, '6', 'Vela P.Dante Villazzano Grotta', '70B442'),
(566, 'AB', 'Via Magazol S.Giorgio Cornacalda', 'None'),
(512, '7', 'Moietto Rosmini Campana Dei Caduti', 'None'),
(1, 'B101', 'Cavalese-Predazzo-Moena-Canazei-Penia', 'None'),
(3, 'B102', 'Trento -  Cembra - Capriana - Cavalese', 'None'),
(169, 'B406', 'Borgo Valsugana -Carzano -Strigno -Samone', 'None'),
(177, 'B418', 'Pergine-Kamauz-Frassilongo-S.Felice F.-Hacleri', 'None'),
(179, 'B417', 'Pergine -Canezza -Viarago -S.Orsola -Palù', 'None'),
(184, 'B407', 'Borgo Valsugana - Telve - Torcegno', 'None'),
(188, 'B423', 'Pergine Vals.-Ischia-Tenna-Levico Terme', 'None'),
(324, 'B640', 'Malè - Rabbi Bagni - Somrabbi', 'None'),
(326, 'B642', 'Malè - Folgarida - Madonna di Campiglio', 'None'),
(328, 'B644', 'Pellizzano - Menas', 'None'),
(330, 'B641', 'Malè - Bolentina', 'None'),
(332, 'B646', 'Malè-Mezzana-Fucine-Vermiglio-Passo Tonale', 'None'),
(334, 'B643', 'Malè - Mezzana - Marilleva 1400', 'None'),
(336, 'B645', 'Malè-Mezzana-Fucine-Cogolo-Peio', 'None'),
(345, 'B611', 'Trento-Mezzocorona-Fai d/Paganella-Andalo-Molveno', 'None'),
(354, 'B624', 'Cles - Mechel', 'None'),
(357, 'B634', 'Cles - Livo - Bresimo - Lanza di Rumo', 'None'),
(364, 'B632', 'Cles - Revò - Castelfondo - Fondo', 'None'),
(366, 'B620', 'Mezzolombardo-Campodenno-Denno-Cles', 'None'),
(368, 'B627', 'Cles - Dermulo - Coredo - Smarano - Sfruz', 'None'),
(371, 'B631', 'Fondo - Tret', 'None'),
(375, 'B630', 'Cles -Dermulo -Dambel -Don -Fondo -P.Mendola', 'None'),
(378, 'B633', 'Cles - Mostizzolo - Cis', 'None'),
(395, 'B615', 'Mezzolombardo - Vigo di Ton -  Toss', 'None'),
(397, 'B623', 'Cles - Pavillo - Tuenno - Nanno - Portolo', 'None'),
(401, 'B625', 'Mollaro - Priò - Vervò - Tres', 'None'),
(703, 'B621', 'Trento-Lavis-Zambana-Nave S.Rocco-Mezzolombardo', 'None'),
(713, 'B601', 'Trento-Dermulo-Cles-Malè', 'None'),
(417, 'B863', 'Linea 3 integrata:Nago-Torbole-Riva-Arco-Bolognano', 'None'),
(420, 'B861', 'Linea 1: Riva -Varone -Arco -S.Giorgio-Brione-Riva', 'None'),
(423, 'B862', 'Linea 2: Riva-Brione-S.Giorgio-Arco-Varone-Riva', 'None'),
(672, 'B869', 'Riva del Garda-Deva-Pranzo-Campi', 'None'),
(352, 'R35', 'FERROVIA TRENTO - MALÉ - MEZZANA', 'None'),
(695, 'R25', 'Servizi Trenitalia - Andata Tn-Bassano', 'None'),
(7, 'B114', 'Casatta di Valfloriana - Palù - Sicina', 'None'),
(55, 'B104', 'Trento-S.Michele a/A-Salorno-Egna-Ora-Cavalese', 'None'),
(60, 'B105', 'Verla - Valternigo - Palù di Giovo', 'None'),
(63, 'B121', 'Montesover - Sover', 'None'),
(65, 'B109', 'Cavalese - Masi di Cavalese', 'None'),
(67, 'B111', 'Cavalese - Carano - Villaggio Veronza', 'None'),
(117, 'B112', 'Cavalese - Daiano - Varena', 'None'),
(120, 'B103', 'Trento - Civezzano - Sover - Cavalese', 'None'),
(130, 'B122', 'Predazzo-P.sso Rolle-Fiera di P.', 'None'),
(136, 'B113', 'Cavalese - Daiano - Carano - Tesero - Cavalese', 'None'),
(151, 'B116', 'Trento - Civezzano - S.Agnese - Bosco', 'None'),
(300, 'B115', 'Pergine - Civezzano', 'None'),
(316, 'B123', 'Moena-Passo  S.Pellegrino-Falcade', 'None'),
(340, 'B107', 'Mezzolombardo - Roverè della Luna', 'None'),
(343, 'B106', 'Mezzocorona Ferrovia - S.Michele - Faedo Pineta', 'None'),
(604, 'B120', 'Cavalese Autostazione - Ospedale', 'None'),
(638, 'B140', 'AAM: Ora-S.Lugano-Castello di Fiemme-Cavalese', 'None'),
(71, 'B201', 'Trento-Vezzano-Sarche-Tione', 'None'),
(73, 'B216', 'Tione-Bolbeno-Ragoli-Montagne', 'None'),
(76, 'B202', 'Trento-Sardagna-Candriai-Vaneze-Vason-Viote', 'None'),
(78, 'B203', 'Vezzano-Ciago-Ranzo-Margone', 'None'),
(80, 'B206', 'Trento-Cadine-Sopramonte-Terlago-MTerlago', 'None'),
(134, 'B205', 'Trento-Vezzano-Sarche-Dro-Arco-Riva', 'None'),
(153, 'B211', 'Riva del Garda-Tenno-Fiavè - Ponte Arche', 'None'),
(155, 'B210', 'Ponte Arche-S.Croce-Cavrasto-Bivedo', 'None'),
(157, 'B215', 'Tione-Pieve di Bono-Storo-Baitoni-Ponte Caffaro', 'None'),
(159, 'B209', 'Ponte Arche-Lundo', 'None'),
(161, 'B208', 'Ponte Arche-S.Lorenzo in B.-Molveno', 'None'),
(164, 'B213', 'Pieve di Bono-Castel Condino-Por', 'None'),
(167, 'B212', 'Pieve di Bono-Praso-Daone', 'None'),
(171, 'B214', 'Riva-Pregasina-Bezzecca-Storo-Pieve di Bono', 'None'),
(175, 'B204', 'Trento-Vezzano Apt-Vigo Cavedine-Riva del Garda', 'None'),
(229, 'B230', 'Trento-Ciago-Monte Terlago-Ranzo-Margone', 'None'),
(322, 'B218', 'Vigo Cavedine - Masi di Vigo Cavedine', 'None'),
(636, 'B231', 'Tione-Pinzolo-Madonna di C.-C.C.Magno', 'None'),
(665, 'B221', 'Riva del Garda-Deva-Pranzo-Campi', 'None'),
(687, 'B261', 'SU Vallelaghi: Terlago-M.Terlago-Ciago-Lon-Vezzano', 'None'),
(110, 'B301', 'Trento-Besenello-Calliano-Rovereto', 'None'),
(181, 'B302', 'Trento -Ravina -Mattarello -Aldeno -Garniga Terme', 'None'),
(186, 'B303', 'Trento-V.Vattaro-Centa-Carbonare-Lavarone-Luserna', 'None'),
(194, 'B311', 'Rovereto-Villa-Nomi-Aldeno', 'None'),
(196, 'B306', 'Rovereto-Calliano-Folgaria-Lavarone', 'None'),
(198, 'B315', 'Rovereto-Terragnolo-Serrada-Folgaria', 'None'),
(200, 'B307', 'Rovereto-Mori-Chizzola-Cornè-Ala-Avio', 'None'),
(203, 'B314', 'Rovereto-Riva-Obra di Vallarsa-Ometto', 'None'),
(215, 'B312', 'Rovereto-Pozzacchio-Raossi-P.Vallarsa-P.Fugazze', 'None'),
(220, 'B310', 'Rovereto-Mori-S.Felice-Ronzo Chienis', 'None'),
(231, 'B305', 'Rovereto-Mori-Brentonico-Saccone', 'None'),
(233, 'B319', 'Besagno-Crosano-Cornè-Saccone', 'None'),
(235, 'B318', 'Valle S.Felice-Manzano-Nomesino', 'None'),
(503, 'B335', "Rovereto-Ala-Masi d'Avio-Avio-Rovereto", 'None'),
(507, 'B334', 'Rovereto-Ala-Sabbionara-Avio-Masi-Rovereto', 'None'),
(526, 'B329', 'Pergine-Calceranica-Bosentino-V.Vattaro', 'None'),
(567, 'B328', 'Trento-Pergine-Caldonazzo-Monterovere-Luserna', 'None'),
(634, 'B332', 'Rovereto-Mori-Riva-Arco-Bolognano', 'None'),
(309, 'B425', 'Pergine Vals.-Masetti-Assizzi-Vignola-Falesina', 'None'),
(494, 'B403', 'Trento - Pergine - Baselga di Pinè - Montesover', 'None'),
(520, 'B401', 'Trento-Pergine V.-Levico T.-Borgo V.', 'None'),
(522, 'B405', 'Borgo V.- Strigno - Castello Tesino', 'None'),
(717, 'B450', 'Servizio sostitutivo treno-Andata', 'None'),
(116, 'B506', 'Fiera di Primiero-Imer-Canal S.Bovo-Caoria', 'None'),
(123, 'B514', 'Trento-Borgo V.-Arten-Fiera di P.-S. Martino C.', 'None'),
(227, 'B507', 'Caoria-Canal S.Bovo-Feltre', 'None'),
(311, 'B511', 'Siror - Fiera di Primiero - Imer - Masi Imer', 'None'),
(618, 'B503', 'Caoria-Imer-Fiera di Primiero-Voltago-Agordo', 'None'),
(647, 'B511', 'Siror - Fiera  P. - Imer - Canal S.B.', 'None'),
(549, 'B461', 'Linea 1 Pergine Valsugana - Madrano - Nogarè', 'None'),
(551, 'B462', 'Linea 2 Pergine-Zivignago-Canezza-Viarago-Serso', 'None'),
(552, 'B466', 'Linea 6 Pergine Valsugana-Costasavina-Roncogno', 'None'),
(554, 'B464', 'Linea 4 Pergine Valsugana - Ischia', 'None'),
(556, 'B463', 'Linea 3 Pergine Valsugana-Masetti-Assizzi-Zava', 'None'),
(640, 'B468', 'Linea 8: Pergine I.-Ospedale Villa Rosa-Zivignago', 'None'),
(568, 'G', 'Gardolo Gardolo Di Mezzo E Spini', 'None'),
(570, 'CM', 'Povo Borino Celva Passo Cimirlo', 'None'),
(607, 'L1', '01 Lavis Pressano Nave S.Felice Sorni', 'None'),
(610, 'L3', '03 Lavis Stazione Fs', 'None'),
(612, 'L4', '04 Lavis Zona Industriale Lavis', 'None'),
(613, 'L2', '02 Lavis Pressano Masi Sp.131 Sorni', 'None'),
(614, 'A', 'P.Dante Ospedale Fersina Clarina P.Dante', 'BABAB7'),
(615, 'M', 'Martignano Montevaccino', 'None'),
(621, 'N', 'Zuffo Via Rosmini Italcementi', 'None'),
(623, '19', 'Stazione Buc M.Baldo Muse Regione', 'None'),
(624, '12', 'P.Dante V.Ghiaie Ravina Romagnano', '95293B'),
(626, '14', 'P.Dante Via Sanseverino Belvedere', 'E490B0'),
(629, '17', 'Dogana Ftm V.Bolzano Lavis Lavs Ftm', '1F9ACF'),
(602, 'S', 'Savignano Pomarolo', 'None'),
(594, '5', 'Ospedale Stazione Isera Villa Lagar.', 'None'),
(563, 'B', 'Ossario Osp. S.Giorgio Osp. Ossario', 'None'),
(590, '3', '03 Peders. Brione Stazione Isera (Lenzima)', 'None'),
(592, '4', 'Villa Lag. Brione Staz. Isera Lenzima', 'None'),
(582, '2', 'Nomi Villa Lagarina Stazione Mori', 'None'),
(601, 'P', 'Castellano Molini Villa Lagarina', 'None'),
(562, 'A', 'Brione Cesari Ospedale Podestà Brione', 'None'),
(598, 'V', 'Volano Besenello Calliano Nomi', 'None'),
(578, '1', '(Volano) Bettini Staz. Lizzana Marco', 'None');