info:
  name: addBus
  type: http
  seq: 6

http:
  method: POST
  url: 127.0.0.1:5000/api/config/addBus
  body:
    type: json
    data: |-
      {
        "token" : "navy-senior-5934",
        "bus_id" : "400"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
