info:
  name: changeName
  type: http
  seq: 3

http:
  method: POST
  url: 127.0.0.1:5000/api/config/changeName
  body:
    type: json
    data: |-
      {
        "token" : "orange-south-1889",
        "name" : "sdrumocelli"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
