info:
  name: setLocation
  type: http
  seq: 4

http:
  method: POST
  url: 127.0.0.1:5000/api/config/setLocation
  body:
    type: json
    data: |-
      {
        "token" : "orange-south-1889",
        "location" : "Trento"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
