info:
  name: unpair
  type: http
  seq: 2

http:
  method: POST
  url: 127.0.0.1:5000/api/config/unpair
  body:
    type: json
    data: |-
      {
        "token" : "orange-south-1889"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
